import type { SkillCase, CategoryTag, User, DashboardStats, CategoryStats } from '@/types';

// 模拟用户
export const mockUsers: User[] = [
  {
    user_id: 'u1',
    email: 'zhang@example.com',
    nickname: '张三',
    avatar_url: '',
    role: 'student',
    status: 'active',
    create_time: '2024-01-01T00:00:00Z',
    update_time: '2024-01-01T00:00:00Z',
  },
  {
    user_id: 'u2',
    email: 'li@example.com',
    nickname: '李四',
    avatar_url: '',
    role: 'tutor',
    status: 'active',
    create_time: '2024-01-01T00:00:00Z',
    update_time: '2024-01-01T00:00:00Z',
  },
  {
    user_id: 'u3',
    email: 'wang@example.com',
    nickname: '王五',
    avatar_url: '',
    role: 'student',
    status: 'active',
    create_time: '2024-01-01T00:00:00Z',
    update_time: '2024-01-01T00:00:00Z',
  },
  {
    user_id: 'u4',
    email: 'zhao@example.com',
    nickname: '赵六',
    avatar_url: '',
    role: 'student',
    status: 'active',
    create_time: '2024-01-01T00:00:00Z',
    update_time: '2024-01-01T00:00:00Z',
  },
  {
    user_id: 'u5',
    email: 'sun@example.com',
    nickname: '孙七',
    avatar_url: '',
    role: 'student',
    status: 'active',
    create_time: '2024-01-01T00:00:00Z',
    update_time: '2024-01-01T00:00:00Z',
  },
  {
    user_id: 'u6',
    email: 'zhou@example.com',
    nickname: '周八',
    avatar_url: '',
    role: 'student',
    status: 'active',
    create_time: '2024-01-01T00:00:00Z',
    update_time: '2024-01-01T00:00:00Z',
  },
];

// 模拟分类标签
export const mockCategories: CategoryTag[] = [
  {
    tag_id: 'c1',
    tag_name: '写作助手',
    tag_code: 'writing',
    icon: '✍️',
    sort_order: 1,
    is_enabled: true,
    case_count: 326,
    create_time: '2024-01-01T00:00:00Z',
  },
  {
    tag_id: 'c2',
    tag_name: '数据分析',
    tag_code: 'data',
    icon: '📊',
    sort_order: 2,
    is_enabled: true,
    case_count: 245,
    create_time: '2024-01-01T00:00:00Z',
  },
  {
    tag_id: 'c3',
    tag_name: '自动化',
    tag_code: 'automation',
    icon: '⚙️',
    sort_order: 3,
    is_enabled: true,
    case_count: 198,
    create_time: '2024-01-01T00:00:00Z',
  },
  {
    tag_id: 'c4',
    tag_name: '开发工具',
    tag_code: 'dev',
    icon: '👨‍💻',
    sort_order: 4,
    is_enabled: true,
    case_count: 167,
    create_time: '2024-01-01T00:00:00Z',
  },
  {
    tag_id: 'c5',
    tag_name: '效率提升',
    tag_code: 'productivity',
    icon: '⚡',
    sort_order: 5,
    is_enabled: true,
    case_count: 134,
    create_time: '2024-01-01T00:00:00Z',
  },
  {
    tag_id: 'c6',
    tag_name: '研究分析',
    tag_code: 'research',
    icon: '🔬',
    sort_order: 6,
    is_enabled: true,
    case_count: 89,
    create_time: '2024-01-01T00:00:00Z',
  },
  {
    tag_id: 'c7',
    tag_name: '设计辅助',
    tag_code: 'design',
    icon: '🎨',
    sort_order: 7,
    is_enabled: true,
    case_count: 56,
    create_time: '2024-01-01T00:00:00Z',
  },
  {
    tag_id: 'c8',
    tag_name: '其他',
    tag_code: 'other',
    icon: '📦',
    sort_order: 8,
    is_enabled: true,
    case_count: 19,
    create_time: '2024-01-01T00:00:00Z',
  },
];

// 模拟案例
export const mockCases: SkillCase[] = [
  {
    case_id: 'case1',
    case_hash: 'hash1',
    title: 'AI写作助手 - 文章生成模板',
    description:
      '强大的AI写作助手，支持多种风格文章生成，包括新闻报道、技术文档、营销文案等。内置智能优化功能。',
    cover_image: '',
    package_file: '/files/case1.zip',
    package_format: 'ClaudeCode',
    status: 'published',
    author_id: 'u1',
    author: mockUsers[0],
    view_count: 3500,
    download_count: 1200,
    favorite_count: 340,
    like_count: 156,
    comment_count: 42,
    report_count: 0,
    is_featured: true,
    sort_weight: 100,
    create_time: '2024-01-01T00:00:00Z',
    update_time: '2024-01-01T00:00:00Z',
    copyright_notice: 'MIT License',
    version: 'v1.0.0',
    tags: [mockCategories[0]],
  },
  {
    case_id: 'case2',
    case_hash: 'hash2',
    title: '数据可视化分析工具',
    description:
      '自动生成各类数据图表，支持多种数据格式导入，一键生成专业可视化报告。',
    cover_image: '',
    package_file: '/files/case2.zip',
    package_format: 'OpenClaw',
    status: 'published',
    author_id: 'u2',
    author: mockUsers[1],
    view_count: 2800,
    download_count: 968,
    favorite_count: 210,
    like_count: 124,
    comment_count: 28,
    report_count: 0,
    is_featured: true,
    sort_weight: 90,
    create_time: '2024-01-02T00:00:00Z',
    update_time: '2024-01-02T00:00:00Z',
    copyright_notice: 'MIT License',
    version: 'v1.0.0',
    tags: [mockCategories[1]],
  },
  {
    case_id: 'case3',
    case_hash: 'hash3',
    title: '办公自动化流程引擎',
    description:
      '自定义办公自动化流程，支持文档处理、邮件管理、数据同步等场景，提升工作效率。',
    cover_image: '',
    package_file: '/files/case3.zip',
    package_format: 'ClaudeCode',
    status: 'published',
    author_id: 'u3',
    author: mockUsers[2],
    view_count: 2400,
    download_count: 856,
    favorite_count: 180,
    like_count: 98,
    comment_count: 21,
    report_count: 0,
    is_featured: false,
    sort_weight: 80,
    create_time: '2024-01-03T00:00:00Z',
    update_time: '2024-01-03T00:00:00Z',
    copyright_notice: 'MIT License',
    version: 'v1.0.0',
    tags: [mockCategories[2]],
  },
  {
    case_id: 'case4',
    case_hash: 'hash4',
    title: '代码审查与优化助手',
    description:
      '智能代码审查工具，自动检测代码问题，提供优化建议，支持多种编程语言。',
    cover_image: '',
    package_file: '/files/case4.zip',
    package_format: 'ClaudeCode',
    status: 'published',
    author_id: 'u4',
    author: mockUsers[3],
    view_count: 2100,
    download_count: 723,
    favorite_count: 150,
    like_count: 87,
    comment_count: 19,
    report_count: 0,
    is_featured: false,
    sort_weight: 70,
    create_time: '2024-01-04T00:00:00Z',
    update_time: '2024-01-04T00:00:00Z',
    copyright_notice: 'MIT License',
    version: 'v1.0.0',
    tags: [mockCategories[3]],
  },
  {
    case_id: 'case5',
    case_hash: 'hash5',
    title: '学习笔记智能整理',
    description:
      '自动整理学习笔记，提取关键知识点，生成思维导图，助力知识系统化管理。',
    cover_image: '',
    package_file: '/files/case5.zip',
    package_format: 'OpenClaw',
    status: 'published',
    author_id: 'u5',
    author: mockUsers[4],
    view_count: 1900,
    download_count: 612,
    favorite_count: 130,
    like_count: 76,
    comment_count: 15,
    report_count: 0,
    is_featured: false,
    sort_weight: 60,
    create_time: '2024-01-05T00:00:00Z',
    update_time: '2024-01-05T00:00:00Z',
    copyright_notice: 'MIT License',
    version: 'v1.0.0',
    tags: [mockCategories[4]],
  },
  {
    case_id: 'case6',
    case_hash: 'hash6',
    title: '研究文献速读助手',
    description:
      '快速提取文献核心内容，生成摘要和关键点，帮助研究者高效筛选文献。',
    cover_image: '',
    package_file: '/files/case6.zip',
    package_format: 'ClaudeCode',
    status: 'published',
    author_id: 'u6',
    author: mockUsers[5],
    view_count: 1600,
    download_count: 489,
    favorite_count: 100,
    like_count: 65,
    comment_count: 12,
    report_count: 0,
    is_featured: false,
    sort_weight: 50,
    create_time: '2024-01-06T00:00:00Z',
    update_time: '2024-01-06T00:00:00Z',
    copyright_notice: 'MIT License',
    version: 'v1.0.0',
    tags: [mockCategories[5]],
  },
];

// 模拟统计数据
export const mockDashboardStats: DashboardStats = {
  total_cases: 1234,
  total_users: 5678,
  total_downloads: 45600,
  pending_review: 23,
  today_upload: 12,
  today_download: 234,
};

// 模拟分类统计
export const mockCategoryStats: CategoryStats[] = [
  { category: '写作助手', count: 326, percentage: 26.4 },
  { category: '数据分析', count: 245, percentage: 19.8 },
  { category: '自动化', count: 198, percentage: 16.0 },
  { category: '开发工具', count: 167, percentage: 13.5 },
  { category: '效率提升', count: 134, percentage: 10.9 },
  { category: '研究分析', count: 89, percentage: 7.2 },
  { category: '设计辅助', count: 56, percentage: 4.5 },
  { category: '其他', count: 19, percentage: 1.5 },
];
